---
# yamllint disable rule:line-length
## Line length rules do not make sense for this file. Comments have still
## been limited to 80 character line length whenever possible.

############################## NETWORKS
## There is no need to create any networks outside this docker-compose file.
## You may customize the network subnets (192.168.90.0/24, 91.0/24, 250.0/24)
## below as you please.
## Docker Compose version 3.5 or higher required to define networks this way.
##
## Note: to enable IPv6 on the bridge network, follow the steps at
## https://docs.docker.com/config/daemon/ipv6/#use-ipv6-for-the-default-bridge-network

networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: $T2_PROXY_SUBNET
          gateway: $T2_PROXY_GATEWAY
        - subnet: $T2_PROXY_IPV6_SUBNET
  socket_proxy:
    name: socket_proxy
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: $SOCKET_PROXY_SUBNET
          gateway: $SOCKET_PROXY_GATEWAY
        - subnet: $SOCKET_PROXY_IPV6_SUBNET
  gluetun_net:
    name: gluetun_net
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: $GLUETUN_SUBNET
          gateway: $GLUETUN_GATEWAY
        - subnet: $GLUETUN_IPV6_SUBNET
  default:
    driver: bridge

############################## SECRETS
secrets:
  postgres_user:
    file: $SECRETSDIR/postgres_user
  postgres_password:
    file: $SECRETSDIR/postgres_password

include:
  ############################## SERVICES
  ## Frontends
  - compose/traefik.yml
  - compose/socket-proxy.yml
  - compose/heimdall.yml
  # - compose/organizr.yml
  ## Security
  - compose/authelia.yml
  # - compose/keycloak.yml
  - compose/authentik.yml
  ## Databases
  - compose/mariadb.yml
  - compose/postgres.yml
  - compose/phpmyadmin.yml
  - compose/adminer.yml
  - compose/redis.yml
  - compose/rediscommander.yml
  ## Media server
  ### Downloads
  - compose/qbit.yml
  - compose/qbit-private.yml
  - compose/qbit-temp.yml
  ### Indexers
  - compose/prowlarr.yml
  # - compose/flaresolverr.yml
  ### Monitoring
  - compose/tautulli.yml
  ### Personal media recorders
  - compose/radarr.yml
  - compose/radarr-4k.yml
  - compose/sonarr.yml
  - compose/sonarr-4k.yml
  - compose/bazarr.yml
  - compose/recyclarr.yml
  - compose/maintainerr.yml
  - compose/audiobookshelf.yml
  - compose/calibre.yml
  - compose/calibre-web.yml
  - compose/lidarr.yml
  ### Requests
  - compose/overseerr.yml
  - compose/ombi.yml
  ### Servers
  - compose/jellyfin.yml
  ## Moved plex to Synology hosted (Intel QuickSync)
  # - compose/plex.yml
  ## Services
  - compose/cf-ddns.yml
  - compose/duckdns.yml
  - compose/docker-gc.yml
  - compose/watchtower.yml
  - compose/vscode.yml
  - compose/filebrowser.yml
  - compose/guacamole.yml
  - compose/dozzle.yml
  - compose/glances.yml
  - compose/dupeguru.yml
  - compose/tdarr.yml
  - compose/tdarr-node.yml
  - compose/handbrake.yml
  - compose/gotify.yml
  ## Web
  - compose/vaultwarden.yml
  - compose/nextcloud.yml
  - compose/firefly.yml
  # - compose/portfolio.yml
  - compose/whoami.yml
  ## VPN
  - compose/wireguard.yml
  - compose/gluetun.yml
  - compose/gluetun-private.yml
  - compose/gluetun-temp.yml
  ## Network services
  # - compose/pi-hole.yml
  - compose/unbound.yml
  - compose/ntp.yml
  ## Minecraft
  # - compose/minecraft.yml
  # - compoase/mc-backup.yml
  # - compose/minecraft-rcon.yml
  ## Miscellaneous
  # - compose/bluebubbles.yml
  - compose/newrelic-infra.yml
