#!/usr/bin/with-contenv bash

# Add to root's crontab
echo '' >> /etc/crontabs/root
echo '# Add script to auto update qbittorrent port' >> /etc/crontabs/root
echo '*/5 * * * * sleep $(shuf --random-source='/dev/urandom' --input-range=60-120 --head-count=1); /scripts/update_qbit_port' >> /etc/crontabs/root
