---
services:
  # audiobookshelf - Self-hosted audiobook and podcast server
  audiobookshelf:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    # ports:
    #   - $AUDIOBOOKSHELF_PORT:13378
    volumes:
      - $APPDIR/audiobookshelf/config:/config
      - $DATADIR/media/audiobooks:/audiobooks
      - $DATADIR/media/podcasts:/podcasts
      - $APPDIR/audiobookshelf/metadata:/metadata # Could be in $DATADIR to minimize storage usage on host
    environment:
      # HOST: 127.0.0.1
      PORT: $AUDIOBOOKSHELF_PORT
      SOURCE: docker
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.audiobookshelf-rtr.entrypoints=https"
      - "traefik.http.routers.audiobookshelf-rtr.rule=Host(`abs.$DOMAINNAME0`)"
      - "traefik.http.routers.audiobookshelf-rtr.tls.options=tls-opts@file"
      ## Middlewares
      - "traefik.http.routers.audiobookshelf-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.audiobookshelf-rtr.service=audiobookshelf-svc"
      - "traefik.http.services.audiobookshelf-svc.loadbalancer.server.port=$AUDIOBOOKSHELF_PORT"
