---
services:
  ## Authentik - an open-source Identity Provider, focused on flexibility and
  ## versatility
  authentik:
    container_name: authentik
    image: ghcr.io/goauthentik/server:latest
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    command: server
    # ports:
    #   - "$AUTHENTIK_PORT:$AUTHENTIK_PORT"
    volumes:
      - $APPDIR/authentik/media:/media
      - $APPDIR/authentik/templates:/templates
    environment:
      ## https://goauthentik.io/docs/installation/configuration
      ## Test configuration with `dcrun2 run --rm authentik-server dump_config`
      ## Use `file://` prefix to load from docker secret
      ## https://goauthentik.io/docs/installation/configuration#about-authentik-configurations
      COMPOSE_PORT_HTTP: $AUTHENTIK_PORT
      # COMPOSE_PORT_HTTPS:
      AUTHENTIK_POSTGRESQL__HOST: $POSTGRES_HOST
      AUTHENTIK_POSTGRESQL__NAME: file:///run/secrets/authentik_postgresql__name
      AUTHENTIK_POSTGRESQL__USER: file:///run/secrets/authentik_postgresql__user
      AUTHENTIK_POSTGRESQL__PORT: $POSTGRES_PORT
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_postgresql__password
      AUTHENTIK_REDIS__HOST: $REDIS_HOST
      AUTHENTIK_REDIS__PORT: $REDIS_PORT
      # AUTHENTIK_REDIS__USERNAME: $REDIS_USER
      AUTHENTIK_REDIS__PASSWORD: file:///run/secrets/authentik_redis__password
      AUTHENTIK_LISTEN__HTTP: "0.0.0.0:${AUTHENTIK_PORT}"
      # AUTHENTIK_LISTEN__HTTPS: "0.0.0.0:"
      AUTHENTIK_LISTEN__LDAP: "0.0.0.0:${AUTHENTIK_LDAP_PORT}"
      AUTHENTIK_LISTEN__LDAPS: "0.0.0.0:${AUTHENTIK_LDAPS_PORT}"
      AUTHENTIK_LISTEN__METRICS: "0.0.0.0:${AUTHENTIK_METRICS_PORT}"
      AUTHENTIK_LISTEN__DEBUG: "0.0.0.0:${AUTHENTIK_DEBUG_PORT}"
      # AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS:
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_LOG_LEVEL: info # trace, debug, info, warning, error
      AUTHENTIK_COOKIE_DOMAIN: $DOMAINNAME0
      # AUTHENTIK_ERROR_REPORTING__ENABLED: 'true'
      AUTHENTIK_EMAIL__HOST: $EMAIL_SERVER
      AUTHENTIK_EMAIL__PORT: $EMAIL_SERVER_PORT
      AUTHENTIK_EMAIL__USERNAME: $EMAIL_SERVER_USER
      AUTHENTIK_EMAIL__PASSWORD: file:///run/secrets/authentik_email__password
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "true"
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: server@authentik.$DOMAINNAME0
      AUTHENTIK_AVATARS: initials
      AUTHENTIK_DEFAULT_USER_CHANGE_NAME: "true"
      AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL: "true"
      AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME: "true"
      AUTHENTIK_GDPR_COMPLIANCE: "true"
      # AUTHENTIK_DEFAULT_TOKEN_LENGTH:
      AUTHENTIK_IMPERSONATION: "true"
      # AUTHENTIK_FOOTER_LINKS:
      # COMPOSE_PORT_HTTPS:
    secrets:
      - authentik_postgresql__name
      - authentik_postgresql__user
      - authentik_postgresql__password
      - authentik_redis__password
      - authentik_secret_key
      - authentik_email__password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authentik-rtr.entrypoints=https"
      - "traefik.http.routers.authentik-rtr.rule=Host(`authentik.$DOMAINNAME0`)"
      - "traefik.http.routers.authentik-rtr.tls.options=tls-opts@file"
      ## Middlewares
      ## Do not use authentication, but use rate limiting and secure headers
      - "traefik.http.routers.authentik-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadbalancer.server.port=$AUTHENTIK_PORT"

  authentik-worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:latest
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    command: worker
    ## `user: root` and the docker socket volume are optional.
    ## See more for the docker socket integration here:
    ## https://goauthentik.io/docs/outposts/integrations/docker
    ## Removing `user: root` also prevents the worker from fixing the
    ## permissions on the mounted folders, so when removing this make sure the
    ## folders have the correct UID/GID (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $APPDIR/authentik/media:/media
      - $APPDIR/authentik/certs:/certs
      - $APPDIR/authentik/templates:/templates
    environment:
      ## https://goauthentik.io/docs/installation/configuration
      ## Test configuration with `dcrun2 run --rm authentik-server dump_config`
      ## Use `file://` prefix to load from docker secret
      ## https://goauthentik.io/docs/installation/configuration#about-authentik-configurations
      AUTHENTIK_POSTGRESQL__HOST: $POSTGRES_HOST
      AUTHENTIK_POSTGRESQL__NAME: "file:///run/secrets/authentik_postgresql__name"
      AUTHENTIK_POSTGRESQL__USER: "file:///run/secrets/authentik_postgresql__user"
      AUTHENTIK_POSTGRESQL__PORT: $POSTGRES_PORT
      AUTHENTIK_POSTGRESQL__PASSWORD: "file:///run/secrets/authentik_postgresql__password"
      AUTHENTIK_REDIS__HOST: $REDIS_HOST
      AUTHENTIK_REDIS__PORT: $REDIS_PORT
      # AUTHENTIK_REDIS__USERNAME: $REDIS_USER
      AUTHENTIK_REDIS__PASSWORD: "file:///run/secrets/authentik_redis__password"
      AUTHENTIK_LISTEN__HTTP: "0.0.0.0:${AUTHENTIK_PORT}"
      # AUTHENTIK_LISTEN__HTTPS: "0.0.0.0:"
      AUTHENTIK_LISTEN__LDAP: "0.0.0.0:${AUTHENTIK_LDAP_PORT}"
      AUTHENTIK_LISTEN__LDAPS: "0.0.0.0:${AUTHENTIK_LDAPS_PORT}"
      AUTHENTIK_LISTEN__METRICS: "0.0.0.0:${AUTHENTIK_METRICS_PORT}"
      AUTHENTIK_LISTEN__DEBUG: "0.0.0.0:${AUTHENTIK_DEBUG_PORT}"
      # AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS:
      AUTHENTIK_SECRET_KEY: "file:///run/secrets/authentik_secret_key"
      AUTHENTIK_LOG_LEVEL: info # trace, debug, info, warning, error
      AUTHENTIK_COOKIE_DOMAIN: authentik.$DOMAINNAME0
      # AUTHENTIK_ERROR_REPORTING__ENABLED: 'true'
      AUTHENTIK_EMAIL__HOST: $EMAIL_SERVER
      AUTHENTIK_EMAIL__PORT: $EMAIL_SERVER_PORT
      AUTHENTIK_EMAIL__USERNAME: $EMAIL_SERVER_USER
      AUTHENTIK_EMAIL__PASSWORD: "file:///run/secrets/authentik_email__password"
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "true"
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: server@authentik.$DOMAINNAME0
      AUTHENTIK_AVATARS: initials
      AUTHENTIK_DEFAULT_USER_CHANGE_NAME: "true"
      AUTHENTIK_DEFAULT_USER_CHANGE_EMAIL: "true"
      AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME: "true"
      AUTHENTIK_GDPR_COMPLIANCE: "true"
      # AUTHENTIK_DEFAULT_TOKEN_LENGTH:
      AUTHENTIK_IMPERSONATION: "true"
      # AUTHENTIK_FOOTER_LINKS:
      # COMPOSE_PORT_HTTPS:
    secrets:
      - authentik_postgresql__name
      - authentik_postgresql__user
      - authentik_postgresql__password
      - authentik_redis__password
      - authentik_secret_key
      - authentik_email__password
