---
secrets:
  cloudflare_ddns_api_token:
    file: $SECRETSDIR/cloudflare_ddns_api_token
services:
  ## Cloudflare DDNS - Dynamic DNS service to update Cloudflare DNS records
  cf-ddns:
    container_name: cf-ddns
    image: favonia/cloudflare-ddns:1
    restart: always
    user: "${PUID}:${PGID}"
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    ## Environmental variables deprecated
    environment:
      TZ: $TZ
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare_ddns_api_token
      DOMAINS: $DOMAINNAME0
      PROXIED: "true"
      UPDATE_CRON: "*/5 * * * *"
      RECORD_COMMENT: "Updated with cf-ddns"
      # SHOUTRRR:  # TODO
    secrets:
      - cloudflare_ddns_api_token
