---
services:
  ## Gluetun - VPN client in a thin Docker container
  ## gluetun-temp is used for temporary files, because nothing is more
  ## permanent than a temporary solution
  gluetun-temp:
    image: ghcr.io/qdm12/gluetun:v3
    container_name: gluetun-temp
    networks:
      gluetun_net:
        ipv4_address: $GLUETUN_TEMP_IPV4
      t2_proxy:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - $GLUETUN_TEMP_HTTP_CONTROL_SERVER_PORT:$GLUETUN_TEMP_HTTP_CONTROL_SERVER_PORT
      ## qBittorrent web UI
      - $QBITTORRENT_TEMP_PORT:$QBITTORRENT_TEMP_PORT
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      VPN_SERVICE_PROVIDER: $GLUETUN_VPN_SERVICE_PROVIDER
      VPN_TYPE: "openvpn"
      # OpenVPN:
      OPENVPN_USER_SECRETFILE: /run/secrets/gluetun_openvpn_user
      OPENVPN_PASSWORD_SECRETFILE: /run/secrets/gluetun_openvpn_password
      ## Fix "WARN [openvpn] 'link-mtu' is used inconsistently"
      ## See https://github.com/qdm12/gluetun/discussions/666
      OPENVPN_FLAGS: "--comp-lzo"
      VPN_PORT_FORWARDING: "on"
      PORT_FORWARD_ONLY: "on"
      VPN_PORT_FORWARDING_PROVIDER: $GLUETUN_TEMP_VPN_SERVICE_PROVIDER
      # Wireguard:
      # WIREGUARD_PRIVATE_KEY:
      # WIREGUARD_ADDRESSES:
      SERVER_COUNTRIES: $GLUETUN_TEMP_SERVER_COUNTRIES
      SERVER_CITIES: $GLUETUN_TEMP_SERVER_CITIES
      SERVER_HOSTNAMES: $GLUETUN_TEMP_SERVER_HOSTNAMES
      TZ: $TZ
      ## See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      UPDATER_PERIOD: "24h"
      HTTP_CONTROL_SERVER_ADDRESS: ":$GLUETUN_TEMP_HTTP_CONTROL_SERVER_PORT"
      HEALTH_VPN_DURATION_INITIAL: "120s"
      HEALTH_VPN_DURATION_ADDITION: "120s"
      HEALTH_SUCCESS_WAIT_DURATION: "120s"
    secrets:
      - gluetun_openvpn_user
      - gluetun_openvpn_password
    labels:
      ## Connectivity issue when restarted with Watchtower
      ## See https://github.com/qdm12/gluetun/issues/641
      - "com.centurylinklabs.watchtower.enable=false"
