---
services:
  ## qBittorrent - an open-source software alternative to µTorrent
  ## qbit-private is used for private trackers
  qbit-private:
    image: lscr.io/linuxserver/qbittorrent:5.0.4
    container_name: qbit-private
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ## We do not want this to be able to communicate locally (except as
    ## specified)
    network_mode: "service:gluetun-private"
    environment:
      # Built-in env variables
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      WEBUI_PORT: $QBITTORRENT_PRIVATE_PORT
      # Custom env variables
      LOG_LEVEL: "WARN" # "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL"
      FILE__QBITTORRENT_USERNAME: /run/secrets/qbittorrent_user
      FILE__QBITTORRENT_PASSWORD: /run/secrets/qbittorrent_pass
      GLUETUN_IPV4: $GLUETUN_PRIVATE_IPV4
      GLUETUN_HTTP_CONTROL_SERVER_PORT: $GLUETUN_PRIVATE_HTTP_CONTROL_SERVER_PORT
    volumes:
      - $APPDIR/qbittorrent-private/config:/config
      ## Add scripts
      - $APPDIR/qbittorrent-private/scripts:/scripts:ro
      ## Space for persistent storage
      - $APPDIR/qbittorrent-private/persistent:/persistent
      ## Add init scripts
      - $APPDIR/qbittorrent-private/custom-cont-init.d:/custom-cont-init.d:ro
      - $APPDIR/qbittorrent-private/custom-services.d:/custom-services.d:ro
      ## Final home for data
      - $DATADIR/torrents-private:/data/torrents-private
      ## Allows for local download before transfer
      - $DOCKERDIR/temp-data/torrents:/temp-data/torrents
    secrets:
      - qbittorrent_user
      - qbittorrent_pass
    labels:
      ## Ensure constant connectivity is prioritized for trackers
      - "com.centurylinklabs.watchtower.enable=false"
