---
services:
  ## qBittorrent - an open-source software alternative to µTorrent
  qbit:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbit
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ## We do not want this to be able to communicate locally (except as
    ## specified)
    network_mode: "service:gluetun"
    environment:
      # Built-in env variables
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      WEBUI_PORT: $QBITTORRENT_PORT
      # Custom env variables
      LOG_LEVEL: "WARN" # "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL"
      FILE__QBITTORRENT_USERNAME: /run/secrets/qbittorrent_user
      FILE__QBITTORRENT_PASSWORD: /run/secrets/qbittorrent_pass
      GLUETUN_IPV4: $GLUETUN_IPV4
      GLUETUN_HTTP_CONTROL_SERVER_PORT: $GLUETUN_HTTP_CONTROL_SERVER_PORT
    volumes:
      - $APPDIR/qbittorrent/config:/config
      ## Add scripts
      - $APPDIR/qbittorrent/scripts:/scripts:ro
      ## Space for persistent storage
      - $APPDIR/qbittorrent/persistent:/persistent
      ## Add init scripts
      - $APPDIR/qbittorrent/custom-cont-init.d:/custom-cont-init.d:ro
      - $APPDIR/qbittorrent/custom-services.d:/custom-services.d:ro
      ## Final home for data
      - $DATADIR/torrents:/data/torrents
      ## Allows for local download before transfer
      - $DOCKERDIR/temp-data/torrents:/temp-data/torrents
    secrets:
      - qbittorrent_user
      - qbittorrent_pass
    labels:
      ## Ensure constant connectivity is prioritized for trackers
      - "com.centurylinklabs.watchtower.enable=false"
