---
services:
  ############################## WEB

  ## Vaultwarden - Unofficial Bitwarden compatible server written in Rust
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ## Run Vaultwarden as non-root user; Currently doesn't work with docker
    ## secrets
    # user: $PUID:$PGID
    # ports:
    #   - $VAULTWARDEN_PORT:$VAULTWARDEN_PORT
    #   - $VAULTWARDEN_WEBSOCKET_PORT:$VAULTWARDEN_WEBSOCKET_PORT
    # depends_on:
    #   - mariadb
    environment:
      ## Note: can append '_FILE' to any env variable to read from a file
      ## (including /run/secrets/my_secret)
      # DATA_FOLDER: data
      DATABASE_URL_FILE: /run/secrets/vaultwarden_mysql_url
      # DATABASE_MAX_CONNS: 10
      # DATABASE_CONN_INIT: ""
      # RSA_KEY_FILENAME: data/rsa_key
      # ICON_CACHE_FOLDER: data/icon_cache
      # ATTACHMENTS_FOLDER: data/attachments
      # SENDS_FOLDER: data/sends
      # TMP_FOLDER: data/tmp
      # TEMPLATES_FOLDER: /path/to/templates
      # RELOAD_TEMPLATES: "false"
      # IP_HEADER: X-Real-IP
      # ICON_CACHE_TTL: 2592000
      # ICON_CACHE_NEGTTL: 259200
      # WEB_VAULT_FOLDER: web-vault/
      WEB_VAULT_ENABLED: "true"
      WEBSOCKET_ENABLED: "true"
      # WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: $VAULTWARDEN_WEBSOCKET_PORT
      SENDS_ALLOWED: "true"
      EMERGENCY_ACCESS_ALLOWED: "true"
      # JOB_POLL_INTERVAL_MS: 30000
      # SEND_PURGE_SCHEDULE: "0 5 * * * *"
      # TRASH_PURGE_SCHEDULE: "0 5 0 * * *"
      # INCOMPLETE_2FA_SCHEDULE: "30 * * * * *"
      # EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE: "0 5 * * * *"
      # EMERGENCY_REQUEST_TIMEOUT_SCHEDULE: "0 5 * * * *"
      ## Enable extended logging, which shows timestamps and targets in the logs
      EXTENDED_LOGGING: "true"
      # LOG_TIMESTAMP_FORMAT: %Y-%m-%d %H:%M:%S.%3f
      # LOG_FILE: /data/vaultwarden.log
      # USE_SYSLOG: "false"
      ## LOG_LEVEL options are: trace, debug, info, warn, error, or off
      LOG_LEVEL: info
      # ENABLE_DB_WAL: "true"
      # DB_CONNECTION_RETRIES: 15
      ICON_SERVICE: bitwarden # internal, bitwarden, duckduckgo, google
      ## 301 (legacy permanent), 302 (legacy temporary), 307 (temporary),
      ## 308 (permanent); Currently legacy redirects work best with
      ## Vaultwarden. Consider permanent redirect for caching
      ICON_REDIRECT_CODE: 308
      # DISABLE_ICON_DOWNLOAD: "false"
      # ICON_DOWNLOAD_TIMEOUT: 10
      # ICON_BLACKLIST_REGEX: '^(192\.168\.0\.[0-9]+|192\.168\.1\.[0-9]+)$'
      ICON_BLACKLIST_NON_GLOBAL_IPS: "true"
      DISABLE_2FA_REMEMBER: "false"
      # EMAIL_ATTEMPTS_LIMIT: 3
      # EMAIL_EXPIRATION_TIME: 600
      EMAIL_TOKEN_SIZE: 12
      SIGNUPS_ALLOWED: "false"
      SIGNUPS_VERIFY: "true"
      # SIGNUPS_VERIFY_RESEND_TIME: 3600
      # SIGNUPS_VERIFY_RESEND_LIMIT: 6
      # ORG_CREATION_USERS:
      ADMIN_TOKEN_FILE: /run/secrets/vaultwarden_admin_token
      DISABLE_ADMIN_TOKEN: "false"
      INVITATIONS_ALLOWED: "true"
      INVITATION_ORG_NAME: Vaultwarden
      # ORG_ATTACHMENT_LIMIT:
      # USER_ATTACHMENT_LIMIT:
      TRASH_AUTO_DELETE_DAYS: 60
      # INCOMPLETE_2FA_TIME_LIMIT: 3  # Minutes
      PASSWORD_ITERATIONS: 250000
      # SHOW_PASSWORD_HINT: "false"
      DOMAIN: https://vault.$DOMAINNAME0
      # ALLOWED_IFRAME_ANCESTORS:
      # LOGIN_RATELIMIT_SECONDS: 60
      # LOGIN_RATELIMIT_MAX_BURST: 10
      # ADMIN_RATELIMIT_SECONDS: 300
      # ADMIN_RATELIMIT_MAX_BURST: 3
      YUBICO_CLIENT_ID_FILE: /run/secrets/vaultwarden_yubico_client_id
      YUBICO_SECRET_KEY_FILE: /run/secrets/vaultwarden_yubico_secret_key
      YUBICO_SERVER: https://api.yubico.com/wsapi/2.0/verify
      DUO_IKEY_FILE: /run/secrets/vaultwarden_duo_ikey
      DUO_SKEY_FILE: /run/secrets/vaultwarden_duo_skey
      DUO_HOST_FILE: /run/secrets/vaultwarden_duo_host
      # AUTHENTICATOR_DISABLE_TIME_DRIFT: "false"
      # ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: $VAULTWARDEN_PORT
      # ROCKET_WORKERS: 10
      # ROCKET_TLS: {certs: "/path/to/certs.pem",key: "/path/to/key.pem"}
      ## Mail specific settings, set SMTP_HOST and SMTP_FROM to enable the mail
      ## service.
      SMTP_HOST: $EMAIL_SERVER
      SMTP_FROM: admin@vault.$DOMAINNAME0
      SMTP_FROM_NAME: Vaultwarden
      SMTP_SECURITY: force_tls # starttls, force_tls, off; Default is starttls
      SMTP_PORT: $EMAIL_SERVER_PORT
      SMTP_USERNAME: $EMAIL_ADDRESS
      SMTP_PASSWORD_FILE: /run/secrets/vaultwarden_smtp_password
      # SMTP_TIMEOUT: 15
      SMTP_AUTH_MECHANISM: Plain # Plain, Login, Xoauth2
      # HELO_NAME:
      # SMTP_DEBUG: "false"
      SMTP_ACCEPT_INVALID_HOSTNAMES: "false"
      SMTP_ACCEPT_INVALID_CERTS: "false"
      REQUIRE_DEVICE_EMAIL: "true"
      # HIBP_API_KEY:
      # RUST_BACKTRACE: full
    volumes:
      - $APPDIR/vaultwarden/data:/data
    secrets:
      - vaultwarden_mysql_url
      - vaultwarden_admin_token
      - vaultwarden_yubico_client_id
      - vaultwarden_yubico_secret_key
      - vaultwarden_duo_ikey
      - vaultwarden_duo_skey
      - vaultwarden_duo_host
      - vaultwarden_smtp_password
    labels:
      - "traefik.enable=true"
      ## UI Labels
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-rtr.entrypoints=https"
      - "traefik.http.routers.vaultwarden-rtr.rule=Host(`vault.$DOMAINNAME0`)"
      - "traefik.http.routers.vaultwarden-rtr.tls.options=tls-opts@file"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-rtr.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadbalancer.server.port=$VAULTWARDEN_PORT"
      ## Websocket Labels
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-websocket-rtr.entrypoints=https"
      - "traefik.http.routers.vaultwarden-websocket-rtr.rule=Host(`vault.$DOMAINNAME0`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket-rtr.tls.options=tls-opts@file"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-websocket-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-websocket-rtr.service=vaultwarden-websocket-svc"
      - "traefik.http.services.vaultwarden-websocket-svc.loadbalancer.server.port=$VAULTWARDEN_WEBSOCKET_PORT"
