---
http:
  routers:
    home-assistant-rtr:
      rule: 'Host(`hass.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        # - chain-authelia
        - chain-no-auth
      service: home-assistant-svc
      tls:
        options: tls-opts@file
  services:
    home-assistant-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://hass.home.arpa:{{env "HOME_ASSISTANT_PORT"}}'
