---
http:
  middlewares:
    nas-stripprefix:
      stripPrefix:
        prefixes:
          - "/bypass_cache"
  routers:
    nas-rtr:
      rule: 'Host(`nas.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia0
        - nas-stripprefix
      service: nas-svc
      tls:
        options: tls-opts@file
  services:
    nas-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://nas.home.arpa:{{env "SYNOLOGY_PORT"}}'
...