---
http:
  routers:
    homebridge-rtr:
      rule: 'Host(`home.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      service: homebridge-svc
      tls:
        options: tls-opts@file
  services:
    homebridge-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://mint.internal:{{env "HOMEBRIDGE_PORT"}}'
...
