---
http:
  routers:
    printer-rtr:
      rule: 'Host(`printer.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      service: printer-svc
      tls:
        options: tls-opts@file
  services:
    printer-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: "http://printer.unifi.internal"
