---
http:
  routers:
    qbittorrent-private-rtr:
      rule: 'Host(`qbit-private.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      service: qbittorrent-private-svc
      tls:
        options: tls-opts@file
  services:
    qbittorrent-private-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://mint.internal:{{env "QBITTORRENT_PRIVATE_PORT"}}'
...
