---
http:
  routers:
    qbittorrent-temp-rtr:
      rule: 'Host(`qbit-temp.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      service: qbittorrent-temp-svc
      tls:
        options: tls-opts@file
  services:
    qbittorrent-temp-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: "http://mint.internal:8170"
