---
http:
  routers:
    qbittorrent-rtr:
      rule: 'Host(`qbit.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia0
      service: qbittorrent-svc
      tls:
        options: tls-opts@file
  services:
    qbittorrent-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://mint.home.arpa:{{env "QBITTORRENT_PORT"}}'
...
