http:
  routers:
    router-rtr:
      rule: 'Host(`router.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia0
        - router-add-cgi-bin
      service: router-svc
      tls:
        options: tls-opts@file
  middlewares:
    router-add-cgi-bin:
      addPrefix:
        prefix: "/cgi-bin"
  services:
    router-svc:
      loadBalancer:
        servers:
          - url: 'http://router.home.arpa'  # or whatever your external host's IP:port is
