http:
  middlewares:
    plex-stripprefix:
      stripPrefix:
        prefixes:
          - "/bypass_cache"
        forceSlash: false
  routers:
    plex-rtr:
      rule: 'Host(`{{env "DOMAINNAME0"}}`) || Host(`p.{{env "DOMAINNAME0"}}`) || Host(`plex.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia0
        - plex-stripprefix
      service: plex-svc
      tls:
        options: tls-opts@file
  services:
    plex-svc:
      loadBalancer:
        servers:
          - url: 'http://nas.home.arpa:{{env "PLEX_PORT"}}'  # or whatever your external host's IP:port is
