---
http:
  routers:
    pi-hole-rtr:
      rule: 'Host(`pihole.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia0
        - pihole-add-admin
      service: pi-hole-svc
      tls:
        options: tls-opts@file
  middlewares:
    pihole-add-admin:
      addPrefix:
        prefix: "/admin"
  services:
    pi-hole-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://pihole.home.arpa'
...
