---
http:
  middlewares:
    plex-stripprefix:
      stripPrefix:
        prefixes:
          - "/bypass_cache"
  routers:
    plex-rtr:
      ## yamllint disable-line rule:line-length
      rule: 'Host(`{{env "DOMAINNAME0"}}`) || Host(`p.{{env "DOMAINNAME0"}}`) || Host(`plex.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia
        - plex-stripprefix
      service: plex-svc
      tls:
        options: tls-opts@file
  services:
    plex-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://nas.internal:{{env "PLEX_PORT"}}'
...
