---
http:
  routers:
    router-rtr:
      rule: 'Host(`router.{{env "DOMAINNAME0"}}`)'
      entryPoints:
        - https
      middlewares:
        - chain-authelia
      service: router-svc
      tls:
        options: tls-opts@file
  services:
    router-svc:
      loadBalancer:
        servers:
          ## Or whatever your external host's IP:port is
          - url: 'http://192.168.1.254'
...
