---
http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers

    chain-basic-auth:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-basic-auth

    chain-authelia:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authelia

    chain-keycloak:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-keycloak

    chain-authentik:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authentik

    # chain-oauth:
    #   chain:
    #     middlewares:
    #       - middlewares-rate-limit
    #       - middlewares-secure-headers
    #       - middlewares-oauth

    chain-nextcloud:
      chain:
        middlewares:
          - middlewares-rate-limit
          - nextcloud-middlewares-secure-headers
          - nextcloud-redirect

    chain-audiobookshelf:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers-audiobookshelf
          ## Need to use audiobookshelf authentication
          # - middlewares-authelia
